# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
r_packages:
    covr

after_success:
    - Rscript -e 'library(covr); codecov()'
    
language: R
sudo: false
cache: packages
